const root=document.body,id=root.dataset.toolId,version=root.dataset.toolVersion;
const events=new Set(['tool_start','tool_complete','tool_export','tool_feedback_submit','tool_cta_click','tool_update_click']);
const formats=new Set(['preview','pdf','json','html','text','summary','png','svg','jpeg','webp','zip']);
const queue=[];
function send(name,details){if(window.zgTrack)return window.zgTrack(name,details);if(queue.length<30)queue.push([name,details]);return Promise.resolve();}
window.zgToolEvent=(name,details={})=>{if(!events.has(name))return Promise.resolve();return send(name,{tool_id:id,tool_version:version,...(formats.has(details.format)?{output_format:details.format}:{})});};
let started=false;function start(){if(!started){started=true;window.zgToolEvent('tool_start');}}
const workspace=document.querySelector('#tool-workspace');workspace?.addEventListener('input',start);workspace?.addEventListener('click',e=>{if(e.target.closest('button'))start();});
document.querySelectorAll('[data-tool-link]').forEach(a=>a.addEventListener('click',async e=>{const delivery=window.zgToolEvent(a.dataset.toolLink);if(e.button||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();await Promise.race([delivery,new Promise(r=>setTimeout(r,1600))]);location.assign(a.href);}));
window.addEventListener('load',()=>{for(const [name,data] of queue.splice(0))window.zgTrack?.(name,data);},{once:true});
const form=document.querySelector('#tool-feedback-form');
if(form){
 const details=document.querySelector('#feedback-details'),status=document.querySelector('#feedback-status'),button=form.querySelector('button[type=submit]');let requestId=crypto.randomUUID(),widget=null,loaded=false,receipt="";
 form.addEventListener("input",event=>{if(event.target.name!=="cf-turnstile-response"){requestId=crypto.randomUUID();receipt="";}});
 async function openFeedback(){if(!details.open||loaded)return;loaded=true;try{const r=await fetch('/api/tool-feedback/config',{cache:'no-store'});if(!r.ok)throw Error();const c=await r.json();if(!c.enabled||!c.sitekey)throw Error();const script=document.createElement('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';await new Promise((resolve,reject)=>{script.onload=resolve;script.onerror=reject;document.head.append(script);});widget=window.turnstile.render('#tool-turnstile',{sitekey:c.sitekey,action:'tool_feedback',callback:()=>{button.disabled=false;status.textContent=receipt||'驗證完成，可以送出。';},'expired-callback':()=>{button.disabled=true;status.textContent='驗證已過期，請重新驗證。';},'error-callback':()=>{button.disabled=true;status.textContent='驗證暫時失敗，請重新開啟頁面。';}});status.textContent='請完成防機器人驗證。';}catch{status.textContent='回報功能暫時無法使用；工具本體仍可正常使用。';loaded=false;}}
 details.addEventListener('toggle',openFeedback);if(details.open)openFeedback();
 form.addEventListener('submit',async e=>{e.preventDefault();if(button.disabled||!form.reportValidity())return;button.disabled=true;status.textContent='送出中…';const fields=Object.fromEntries(new FormData(form));const data={tool_id:id,version,locale:'zh-TW',type:fields.type,nickname:fields.nickname,title:fields.title,body:fields.body,email:fields.email,website:fields.website,public_opt_in:form.elements.public_opt_in.checked,request_id:requestId,turnstile_token:window.turnstile.getResponse(widget)};try{const r=await fetch('/api/tool-feedback/submit',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});const result=await r.json();if(!r.ok||!result.ok)throw Error(r.status===429?'送出太頻繁，請稍後再試。':'送出未完成，請重新驗證後再試。');receipt='已收到，待審核。回報編號：'+result.id;status.textContent=receipt;window.zgToolEvent('tool_feedback_submit');form.reset();requestId=crypto.randomUUID();}catch(error){status.textContent=error.message;}finally{window.turnstile.reset(widget);}});
 let cursor=null,commentsLoaded=false;const more=document.querySelector('#comments-more'),list=document.querySelector('#tool-comments');
 more.addEventListener('click',async()=>{more.disabled=true;try{const p=new URLSearchParams({tool:id});if(cursor)p.set('cursor',cursor);const r=await fetch('/api/tool-feedback/messages?'+p,{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();if(!commentsLoaded){list.replaceChildren();commentsLoaded=true;}if(!data.items.length&&!list.children.length)list.textContent='目前沒有公開留言，歡迎留下第一個建議。';for(const row of data.items){const card=document.createElement('article'),h=document.createElement('h4'),meta=document.createElement('small'),body=document.createElement('p');h.textContent=row.title;meta.textContent=row.nickname+' · '+row.created_at.slice(0,10)+' · '+({received:'已收到',reviewing:'評估中',completed:'已完成'}[row.state]||'已收到');body.textContent=row.body;card.append(h,meta,body);if(row.reply){const p=document.createElement('p');p.className='reply';p.textContent='榛菓回覆：'+row.reply;card.append(p);}list.append(card);}cursor=data.cursor;more.hidden=!cursor;more.textContent='載入更多';}catch{if(!commentsLoaded)list.textContent='留言暫時無法載入，請稍後再試。';}finally{more.disabled=false;}});
}
