export const adminHtml = `<!doctype html><html lang="zh-TW"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>工具回報審核｜榛菓</title><style>body{margin:0;background:#f7f5ef;color:#20352d;font:16px/1.65 system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:32px 20px}header{display:flex;justify-content:space-between;gap:20px;align-items:center}h1{font-size:30px}button,select,input,textarea{font:inherit}button{padding:10px 20px;background:#244a3a;color:white;border:0;border-radius:5px;cursor:pointer}button:disabled{opacity:.5}select,input,textarea{padding:9px;border:1px solid #bbc7bd;border-radius:4px;box-sizing:border-box;max-width:100%}label{display:grid;gap:5px;margin:12px 0}textarea{width:100%;min-height:100px}article{background:white;border:1px solid #d9dfd7;margin:24px 0;padding:24px;border-radius:8px}.private{white-space:pre-wrap;background:#f2f0eb;padding:16px;color:#473f39;overflow-wrap:anywhere}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.status{color:#8d3225;white-space:pre-wrap}.muted{color:#66716b;font-size:14px}summary{cursor:pointer;font-weight:700}:focus-visible{outline:3px solid #cc654d;outline-offset:3px}@media(max-width:650px){.grid{grid-template-columns:1fr}article{padding:16px}}</style><main><header><div><small>ZHENGUOCOOL / STAFF</small><h1>工具回報審核</h1></div><a href="/">返回 staff</a></header><p>原始回報與 Email 僅供管理。公開前請在下方欄位整理去個資版本；未同意公開的回報不能核准。通知與自動清理尚未啟用。</p><label>審核分類<select id="filter"><option value="pending">待審核</option><option value="approved">已公開</option><option value="rejected">不公開</option><option value="hidden">已隱藏</option></select></label><p id="status" role="status"></p><div id="list"></div><button id="more" hidden>載入較早回報</button></main><script>
const q=s=>document.querySelector(s),labels={received:'已收到',reviewing:'評估中',completed:'已完成'};let before=null,busy=false;
async function load(reset=true){if(busy)return;busy=true;q('#status').textContent='讀取中…';try{if(reset){q('#list').replaceChildren();before=null;}const params=new URLSearchParams({moderation:q('#filter').value});if(before)params.set('before',before);const r=await fetch('/tool-feedback/api/messages?'+params,{cache:'no-store'});if(!r.ok)throw Error('無法讀取（'+r.status+'），請確認以授權帳號登入。');const data=await r.json();for(const row of data.items)render(row);before=data.cursor;q('#more').hidden=!before;q('#status').textContent=data.items.length?'本批 '+data.items.length+' 筆':'目前沒有回報。';}catch(e){q('#status').textContent=e.message;}finally{busy=false;}}
function render(row){const card=document.createElement('article');const title=document.createElement('h2');title.textContent=row.title;card.append(title);const meta=document.createElement('p');meta.className='muted';meta.textContent=row.tool_id+' / '+row.version+' / '+row.created_at+' / '+row.id;card.append(meta);const original=document.createElement('div');original.className='private';original.textContent='暱稱：'+row.nickname+'\\nEmail：'+(row.email||'未提供')+'\\n同意公開：'+(row.public_opt_in?'是':'否')+'\\n\\n'+row.body;card.append(original);
const form=document.createElement('form');form.innerHTML='<div class="grid"><label>審核狀態<select name="moderation"><option value="pending">待審核</option><option value="approved">公開</option><option value="rejected">不公開</option><option value="hidden">隱藏</option></select></label><label>處理狀態<select name="state"><option value="received">已收到</option><option value="reviewing">評估中</option><option value="completed">已完成</option></select></label></div><div class="grid"><label>公開標題<input name="public_title" maxlength="100"></label><label>公開暱稱<input name="public_nickname" maxlength="40"></label></div><label>公開正文（先移除聯絡資料及機密）<textarea name="public_body" maxlength="2000"></textarea></label><label>管理員公開回覆<textarea name="public_reply" maxlength="2000"></textarea></label><button type="submit">儲存審核結果</button><p class="status" role="status"></p>';
for(const name of ['moderation','state','public_title','public_nickname','public_body','public_reply'])form.elements[name].value=row[name]||'';
if(!row.public_opt_in)form.querySelector('option[value="approved"]').disabled=true;
form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button'),status=form.querySelector('.status');button.disabled=true;status.textContent='儲存中…';try{const body=Object.fromEntries(new FormData(form));body.revision=row.revision;const r=await fetch('/tool-feedback/api/messages/'+row.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(r.status===409?'資料已由其他視窗更新，請重新載入後再審核。':data.error==='public_consent_required'?'此回報未同意公開，或公開欄位尚未填妥。':'儲存失敗，請稍後再試。');row.revision++;status.textContent='已儲存';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});card.append(form);q('#list').append(card);}
q('#filter').addEventListener('change',()=>load());q('#more').addEventListener('click',()=>load(false));load();
</script></html>`;
