import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import vm from 'node:vm';
import worker,{submission,moderationInput,publicRecord} from '../workers/tool-feedback/index.mjs';
import {claimsIdentity,adminIdentity} from '../workers/tool-feedback/access.mjs';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync(new URL('../workers/tool-feedback/schema.sql',import.meta.url),'utf8'));
sqlite.exec(fs.readFileSync(new URL('../workers/tool-feedback/002-audit.sql',import.meta.url),'utf8'));
const DB={prepare(sql){return {bind(...values){return {async first(){return sqlite.prepare(sql).get(...values)||null;},async all(){return {results:sqlite.prepare(sql).all(...values)};},async run(){const r=sqlite.prepare(sql).run(...values);return {meta:{changes:r.changes}};}};}};},async batch(stmts){sqlite.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const env={DB,ENABLED:'true',TURNSTILE_SECRET:'test-server-secret',TURNSTILE_SITEKEY:'test-sitekey',RATE_SALT:'test-rate-salt',TEAM_DOMAIN:'https://test.cloudflareaccess.com',POLICY_AUD:'test-audience',ADMIN_EMAIL:'owner@example.com'};
const sample={request_id:crypto.randomUUID(),tool_id:'quotation',version:'1.0.0',locale:'zh-TW',type:'suggestion',nickname:'示意訪客',title:'新增模板',body:'這是測試內容 <img onerror=alert(1)>',email:'private@example.com',public_opt_in:true,website:'',turnstile_token:'good'};
assert.throws(()=>submission({...sample,title:''}));assert.throws(()=>submission({...sample,body:'x'.repeat(2001)}));assert.throws(()=>submission({...sample,tool_id:'arbitrary'}));assert.throws(()=>submission({...sample,email:'111@111'}));assert.throws(()=>moderationInput({moderation:'approved',state:'received',revision:0,public_title:'x',public_body:'x'},{public_opt_in:0}));
const originalFetch=globalThis.fetch;let verificationCalls=0;
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'key'};
globalThis.fetch=async(url,options)=>{if(String(url).endsWith('/siteverify')){verificationCalls++;const token=JSON.parse(options.body).response;return Response.json({success:token==='good',hostname:token==='wrong-host'?'evil.example':'zhenguocool.com',action:'tool_feedback'});}if(String(url).endsWith('/certs'))return Response.json({keys:[jwk]});throw Error('unexpected_network');};
const req=(path,body,ip='1.2.3.4')=>new Request('https://feedback.internal/public/'+path,{method:body?'POST':'GET',headers:{origin:'https://zhenguocool.com','content-type':'application/json','CF-Connecting-IP':ip},...(body?{body:JSON.stringify(body)}:{})});
let r=await worker.fetch(req('submit',sample),env);assert.equal(r.status,201);const {id}=await r.json();
r=await worker.fetch(req('submit',sample),env);assert.equal(r.status,200);assert.equal((await r.json()).id,id);assert.equal(verificationCalls,1);assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM feedback').get().n,1);
assert.equal((await worker.fetch(req('submit',{...sample,title:'changed'}),env)).status,409);
r=await worker.fetch(req('messages?tool=quotation'),env);assert.deepEqual((await r.json()).items,[]);
const b64=b=>Buffer.from(b).toString('base64url');async function jwt(claims={}){const h=b64(JSON.stringify({alg:'RS256',kid:'key'})),p=b64(JSON.stringify({iss:env.TEAM_DOMAIN,aud:[env.POLICY_AUD],exp:Date.now()/1000+300,email:env.ADMIN_EMAIL,...claims}));return h+'.'+p+'.'+b64(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(h+'.'+p)));}
assert.throws(()=>claimsIdentity({iss:env.TEAM_DOMAIN,aud:['wrong'],exp:Date.now()/1000+300,email:env.ADMIN_EMAIL},env));
const access=await jwt();const adminReq=(path,body,token=access)=>new Request('https://staff.zhenguocool.com/tool-feedback'+path,{method:body?'PATCH':'GET',headers:{origin:'https://staff.zhenguocool.com','content-type':'application/json','Cf-Access-Jwt-Assertion':token},...(body?{body:JSON.stringify(body)}:{})});
assert.equal(await adminIdentity(adminReq('/'),env),env.ADMIN_EMAIL);assert.equal((await worker.fetch(adminReq('/','',await jwt({email:'other@example.com'})),env)).status,403);assert.equal((await worker.fetch(adminReq('/','',await jwt({exp:0})),env)).status,403);assert.equal((await worker.fetch(new Request('https://staff.zhenguocool.com/tool-feedback/',{headers:{'Cf-Access-Authenticated-User-Email':env.ADMIN_EMAIL}}),env)).status,403);
const patch={revision:0,moderation:'approved',state:'reviewing',public_title:'已整理標題',public_body:'已移除私密內容',public_nickname:'訪客',public_reply:'已收到建議。'};
assert.equal((await worker.fetch(adminReq('/api/messages/'+id,patch),env)).status,200);assert.equal((await worker.fetch(adminReq('/api/messages/'+id,patch),env)).status,409);
r=await worker.fetch(req('messages?tool=quotation'),env);const result=await r.json();assert.equal(result.items.length,1);assert.equal(result.items[0].body,patch.public_body);assert.ok(!JSON.stringify(result).includes(sample.email));assert.ok(!JSON.stringify(result).includes(sample.body));assert.equal(sqlite.prepare('SELECT COUNT(*) n FROM feedback_audit').get().n,1);
assert.equal((await worker.fetch(adminReq('/api/messages/'+id,{...patch,revision:1,moderation:'hidden'}),env)).status,200);assert.equal((await(await worker.fetch(req('messages?tool=quotation'),env)).json()).items.length,0);
const badOrigin=req('submit',{...sample,request_id:crypto.randomUUID()});badOrigin.headers.set('origin','https://evil.example');assert.equal((await worker.fetch(badOrigin,env)).status,403);
const badAdminOrigin=adminReq('/api/messages/'+id,{...patch,revision:2});badAdminOrigin.headers.set('origin','https://evil.example');assert.equal((await worker.fetch(badAdminOrigin,env)).status,403);
sqlite.exec("CREATE TRIGGER reject_audit BEFORE INSERT ON feedback_audit BEGIN SELECT RAISE(ABORT,'test_audit_failure'); END;");
assert.equal((await worker.fetch(adminReq('/api/messages/'+id,{...patch,revision:2}),env)).status,503);assert.equal(sqlite.prepare('SELECT revision FROM feedback WHERE id=?').get(id).revision,2);sqlite.exec('DROP TRIGGER reject_audit');
for(let i=0;i<32;i++)sqlite.prepare('INSERT INTO feedback(id,request_id,request_hash,tool_id,version,locale,type,nickname,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(crypto.randomUUID(),crypto.randomUUID(),'test','quotation','1.0.0','zh-TW','question','test','test','test','2026-09-08T00:00:00.000Z','2026-09-08T00:00:00.000Z');
const firstPage=await(await worker.fetch(adminReq('/api/messages'),env)).json();assert.equal(firstPage.items.length,30);assert.ok(firstPage.cursor);const nextPage=await(await worker.fetch(adminReq('/api/messages?before='+encodeURIComponent(firstPage.cursor)),env)).json();assert.equal(nextPage.items.length,2);assert.equal(new Set([...firstPage.items,...nextPage.items].map(x=>x.id)).size,32);
assert.equal((await worker.fetch(req('submit',{...sample,request_id:crypto.randomUUID(),turnstile_token:'bad'},'2.2.2.2'),env)).status,403);
for(let i=0;i<30;i++)await worker.fetch(req('submit',{...sample,request_id:crypto.randomUUID(),turnstile_token:'bad'},'3.3.3.3'),env);assert.equal((await worker.fetch(req('submit',{...sample,request_id:crypto.randomUUID()},'3.3.3.3'),env)).status,429);
assert.equal((await worker.fetch(req('submit',{...sample,request_id:crypto.randomUUID(),body:'a'.repeat(17000)}),env)).status,413);
assert.equal((await worker.fetch(req('submit',sample),{...env,ENABLED:'false'})).status,503);
assert.equal((await worker.fetch(new Request('https://staff.zhenguocool.com/public/messages?tool=quotation'),env)).status,404);
assert.ok(!('email' in publicRecord({email:'secret'})));globalThis.fetch=originalFetch;sqlite.close();console.log('PASS: feedback validation, atomic storage, replay, moderation consent, public projection, audit, auth, CSRF boundary, rate limit, size and fail-closed');
let configCalls=0;const uiStatus={textContent:''},uiDetails=Object.assign(new EventTarget(),{open:true}),uiButton={disabled:true},uiForm=Object.assign(new EventTarget(),{querySelector:()=>uiButton});
const uiNodes={'#tool-feedback-form':uiForm,'#feedback-details':uiDetails,'#feedback-status':uiStatus,'#comments-more':new EventTarget(),'#tool-comments':{}};
vm.runInNewContext(fs.readFileSync(new URL('../web-assets/public-tools/common.mjs',import.meta.url),'utf8'),{document:{body:{dataset:{toolId:'quotation',toolVersion:'1.0.0'}},querySelector:s=>uiNodes[s]||null,querySelectorAll:()=>[]},window:{addEventListener(){}},crypto,fetch:async()=>{configCalls++;return Response.json({enabled:false});},URLSearchParams,Event,setTimeout});
await new Promise(setImmediate);assert.equal(configCalls,1);assert.match(uiStatus.textContent,/暫時無法使用/);console.log('PASS: feedback opened before module initialization is initialized once');
