const figure = (content, caption) => `<figure class="explainer">${content}<figcaption>${caption}</figcaption></figure>`;

const storyFrame = (n, type, title, description) => {
  const id = `story-${type}-${n}`;
  const cup = (x, y, k = 1) => `<g transform="translate(${x} ${y}) scale(${k})"><ellipse cx="85" cy="240" rx="100" ry="16" fill="#4c503d" opacity=".09"/><path d="M20 26Q85 40 150 26L134 225Q85 242 36 225Z" fill="url(#${id}-glass)" stroke="#676458" stroke-width="2"/><path d="M27 85Q85 97 143 85L132 220Q85 235 38 220Z" fill="url(#${id}-tea)"/><ellipse cx="85" cy="85" rx="58" ry="10" fill="#c79152" opacity=".8"/><g fill="#f4ebd2" fill-opacity=".58" stroke="#efe6d3" stroke-width="1"><path d="M47 75L80 70L86 102L53 108Z"/><path d="M87 108L123 96L133 123L102 138Z"/><path d="M47 141L78 133L86 164L53 169Z"/></g><path d="M43 43L53 213M126 43L118 211" fill="none" stroke="#fffdf4" stroke-opacity=".55" stroke-width="5"/><ellipse cx="85" cy="25" rx="68" ry="14" fill="#efeee4" fill-opacity=".72" stroke="#676458" stroke-width="2"/><ellipse cx="85" cy="22" rx="61" ry="9" fill="none" stroke="#a8a393"/><g fill="#fffdf4" opacity=".6"><circle cx="113" cy="151" r="2"/><circle cx="102" cy="180" r="3"/><circle cx="65" cy="185" r="2"/><circle cx="125" cy="76" r="2"/></g></g>`;
  const window = '<path d="M35 20H605V270H35Z" fill="#dce2d3"/><path d="M42 214L220 112L342 181L474 91L600 161V267H42Z" fill="#bfcdbb" opacity=".65"/><path d="M35 270H605M319 20V270" fill="none" stroke="#8d9383" stroke-width="9"/><path d="M34 272H608L640 308H0Z" fill="#c6b49a"/><path d="M0 320H640M0 342H640M0 373H640" stroke="#baa98e" stroke-width="1"/>';
  const street = '<path d="M0 0H640V400H0Z" fill="#e7e9df"/><path d="M0 60L260 123V262L0 368ZM640 22L399 120V262L640 388Z" fill="#d1d6ca" stroke="#858e80" stroke-width="2"/><path d="M260 262L0 400M399 262L640 400M0 338L640 350M156 303L528 308M232 279L437 281" fill="none" stroke="#acb29f"/><path d="M46 85V303M104 99V288M169 113V278M220 125V265M590 61V323M527 85V300M466 108V279" stroke="#8f998a" stroke-width="2"/><path d="M0 153L260 177M0 226L260 218M640 145L399 178M640 238L399 221" stroke="#8f998a" stroke-width="2"/><path d="M333 81V261" stroke="#7c8678" stroke-width="5"/><path d="M330 99Q255 80 280 45Q336 8 370 64Q418 114 335 121Z" fill="#99ae91"/><path d="M311 113L333 179L362 97" fill="none" stroke="#7c8678" stroke-width="3"/><path d="M70 312H217V329H70ZM89 329V364M200 329V352" fill="#b39475" stroke="#6f7162" stroke-width="3"/>';
  let scene;
  if (type === 'walk') scene = street;
  else if (type === 'window') scene = window + cup(358, 150, .72);
  else if (type === 'detail') scene = '<path d="M0 295L640 235V400H0Z" fill="#d8c7a9"/>' + cup(140, -85, 2);
  else if (type === 'sip') scene = '<path d="M0 320H640M40 334H570" stroke="#c9bc9f" stroke-width="2"/>' + cup(174, 55, 1.12) + '<path d="M423 178Q483 202 464 240M444 172Q504 204 481 251" fill="none" stroke="#9fae96" stroke-width="2"/>';
  else scene = '<path d="M0 284L640 251V400H0Z" fill="#e2d5bd"/><path d="M75 371L532 300M125 397L606 321" stroke="#c9b998" stroke-width="1"/>' + cup(type === 'cup' && n === '03' ? 324 : 215, 55, 1.12);
  return `<div class="frame"><svg viewBox="0 0 640 400" role="img" aria-label="${title} storyboard shot"><defs><linearGradient id="${id}-glass" x2="1" y2=".2"><stop stop-color="#f4f0de" stop-opacity=".85"/><stop offset=".45" stop-color="#fffdf8" stop-opacity=".2"/><stop offset="1" stop-color="#d1d5c5" stop-opacity=".7"/></linearGradient><linearGradient id="${id}-tea" x2=".7" y2="1"><stop stop-color="#bc8945"/><stop offset=".55" stop-color="#ad7136"/><stop offset="1" stop-color="#cb9451"/></linearGradient></defs><rect width="640" height="400" fill="#f1ede2"/>${scene}<path d="M16 35V16H35M605 16H624V35M16 365V384H35M605 384H624V365" stroke="#9c9b87" stroke-width="1" fill="none"/></svg><p><b>${n} ${title}</b><br>${description}</p></div>`;
};

const views = [1200, 1500, 1800, 2000, 2200, 2400, 2600, 3000, 3300, 30000];
const formatNumber = value => value.toLocaleString('en-US');
const mean = views.reduce((sum, value) => sum + value, 0) / views.length;
const median = (views[4] + views[5]) / 2;

export const enCore = {
  'reading-social-comment-signals': {
    title: 'Lots of comments—does that mean the content works? Reading the different signals in engagement',
    description: 'From giveaway instructions and generic praise to product questions and usage experiences, practice reading comments in context instead of treating engagement volume as direct purchase intent.',
    category: 'Social observations',
    coverAlt: 'A phone, notebook, sheets of paper, and pencil in natural window light, evoking the pause of reading and organizing what you see.',
    caption: 'AI-generated scene illustration | Pause, then organize the signals you can actually see. Not real private messages or work records.',
    toc: [
      ['signals', 'Start with what people are responding to'],
      ['context', 'Put comments back in their original context'],
      ['practice', 'Leave a question that can be verified']
    ],
    body: `<p class="lead">Imagine two videos each receive one hundred comments. One is filled with repeated “Followed and shared,” while on the other people ask about sweetness and storage, and describe their own experience. The comment counts are identical, but they tell you different things.</p>
    <p>This is a hypothetical scenario, not a ZhenguoCool client result. The point of this note is to break “lots of engagement” into more concrete observations. Comments are neither purchase records nor a direct readout of what an audience feels; they are more like a small window showing which part of the content some people who choose to speak up are reacting to.</p>
    <section id="signals" class="chapter"><h2>01 / Start with what people are responding to</h2><p>Do not sort every comment into good or bad too quickly. Start with the comment itself and use a category system that is easy to organize; the four types below are neither official platform rules nor a ranking from low to high performance.</p>
    <figure class="explainer"><div class="signal-grid"><div class="note-panel"><span class="number">A</span><h3>Task response</h3><blockquote>“I tagged a friend—want to join!”</blockquote><p>What it shows: Someone responded to the activity prompt.</p><p class="limit">What it cannot prove: They intend to buy the product.</p></div><div class="note-panel"><span class="number">B</span><h3>General praise</h3><blockquote>“This looks so good.”</blockquote><p>What it shows: The visual or presentation prompted a response.</p><p class="limit">What it cannot prove: They remember the brand.</p></div><div class="note-panel"><span class="number">C</span><h3>Product question</h3><blockquote>“Can I order it without sugar?”</blockquote><p>What it shows: A specific information need has appeared.</p><p class="limit">What it cannot prove: The person asking will definitely buy.</p></div><div class="note-panel"><span class="number">D</span><h3>Usage experience</h3><blockquote>“The tea flavor was stronger in the cup I bought last week.”</blockquote><p>What it shows: Someone reports a personal usage experience.</p><p class="limit">What it cannot prove: The experience has been verified or is representative.</p></div></div><figcaption>Figure 1 | All comments above are fictional examples. Categories can overlap; when you cannot tell, keep “Other / uncertain.”</figcaption></figure>
    <p>A person may first praise the visual and then ask about product specifications; there is no need to force the two comments into mutually exclusive boxes. If a comment complains about delivery, challenges a claim, or discusses a joke unrelated to the product, note it separately. Do not delete it just to make the results look neat.</p></section>
    <section id="context" class="chapter"><h2>02 / Put comments back in their original context</h2><p>“I want to buy it” may express a real need, or it may simply be a riff; “Does this really work?” may be a genuine question, or sarcasm. Pulling out a few words loses the original tone and conversation. When you read, look at the post, the comment thread, the creator’s replies, and whether a giveaway or question prompt shaped the discussion.</p>
    <p>Record how you chose the sample, too. Looking only at pinned or top-ranked comments cannot represent the whole discussion; choosing only the sentences you like makes it easier to find the answer you already wanted to believe. If you are doing a quick read, say plainly that you spot-checked the first twenty visible comments instead of presenting it as an audience-wide survey.</p>
    <figure class="explainer"><ol class="steps"><li><span>01</span><h3>Classify first</h3><p>Record whether the comment is about the visual, product, activity, or something else.</p></li><li><span>02</span><h3>Add context</h3><p>Revisit the original post and conversation, leaving room for a giveaway prompt, genuine question, or sarcasm.</p></li><li><span>03</span><h3>Keep it for verification</h3><p>Rewrite an assumption as the next question that needs more data.</p></li></ol><figcaption>Figure 2 | A sample organizing flow: move from what you can see to a question to confirm, rather than jumping straight to a performance conclusion.</figcaption></figure>
    <p>If you want to compare two pieces of content, keep the observation window as consistent as possible. A video published moments ago and one that has accumulated discussion for weeks are naturally at different stages. Record the sample date, visible scope, and selection method so you know what you are comparing later.</p></section>
    <section id="practice" class="chapter"><h2>03 / Leave a question that can be verified</h2><p>Instead of writing “This post is highly effective,” try: “Sweetness questions appeared multiple times in the sampled comments; did the video leave out the options?” That sentence does not pretend to know the conversion result, but it can help the next piece of content add the missing information. Then check whether a clear answer already exists, or explain it differently in the next post and observe whether the question changes.</p>
    <aside class="margin-note"><strong>A small exercise for today</strong><p>Choose one public post and read ten comments you can see. For each, note a “summary of the exact wording,” “context,” and “what is still uncertain.” At the end, write only one question worth continuing to investigate.</p></aside>
    <p>What matters is not turning comments into a score that looks precise, but slowing your judgment by half a step: know what you saw, and know what still has no evidence. People who leave no comments are still part of the audience; this method simply cannot hear their voices. A handful of comments cannot support claims about what every audience member thinks.</p></section>
    <div class="source-note"><h2>Editorial and material notes</h2><p>This is a reading exercise proposed by the ZhenguoCool editorial team, not a platform-metric definition or performance study. The categories, comments, and scenarios are original examples; no client data, real accounts, or private conversations were used.</p></div>`,
    cover: {
      headline: ['Beyond comments', 'Read the signals.'],
      sub: ['Break the buzz apart,', 'then read each line in context.'],
      category: 'Social observations / 01',
      labels: ['OBSERVE', 'CONTEXT']
    }
  },
  'beverage-content-storytelling': {
    title: 'The same drink, but why does one person shoot it like an ad while another makes it feel like everyday life?',
    description: 'Using a fictional drink and a six-panel storyboard, compare product-led and situation-led narrative starting points, and observe how shots, captions, and information work together.',
    category: 'Content studies',
    coverAlt: 'A translucent amber iced tea on a wooden table by a window, with a blurred streetscape behind it, evoking an everyday story.',
    caption: 'AI-generated scene illustration | The same drink, a different starting point. Not a real product, shoot, or collaboration case.',
    toc: [
      ['opening', 'Decide where the story starts'],
      ['frames', 'See two paths through six storyboard frames'],
      ['information', 'Give the image and information separate jobs']
    ],
    body: `<p class="lead">The same drink can begin with a close-up of the cup, or with someone finishing a hot walk and sitting down to rest. The first route shows us the product; the second brings us into a situation. The difference is not only whether the image looks good, but what question gets asked first.</p>
    <p>We will use a fictional tea with no brand and no real performance data as a practice example. This is not a claim that everyday storytelling is always more effective than an ad-like approach, nor an invitation to disguise a commercial collaboration as ordinary life. We are simply taking the story apart to see what each shot is responsible for.</p>
    <section id="opening" class="chapter"><h2>01 / Decide where the story starts</h2><p>A product-led opening might ask, “What is this, and what makes it distinctive?” The image first establishes the cup, ingredients, or preparation, then adds a description of how it tastes. The information is concentrated, which suits content that needs to show details clearly; the trade-off is that if every frame repeats a selling point, viewers may not know what the drink has to do with their own lives.</p>
    <p>A situation-led opening instead asks, “When would I encounter this drink?” It could be the end of a work session, a walk with friends, or something to pair with lunch. The product is part of the situation, but if the story finishes without explaining the drink, viewers may remember only the walk and the scenery.</p>
    <p>These are not opposing styles. A piece can enter through an everyday moment and then cut to product detail. The thing to avoid is not one particular format, but a sequence with many shots and much information whose relationship to one another is impossible to find.</p></section>
    <section id="frames" class="chapter"><h2>02 / See two paths through six storyboard frames</h2><p>Try arranging three shots for the same fictional tea. Look at the order of the images before reading the text under each frame; this storyboard represents narrative functions, not an ideal duration or success formula for any particular platform.</p>
    ${figure(`<div class="story-columns"><div><h3>Path A / Product first</h3>${storyFrame('01', 'cup', 'Show the drink', 'Place the cup on a clean table to establish the subject.')}${storyFrame('02', 'detail', 'Move in for detail', 'Use a close-up of tea and ice to explain the visible features.')}${storyFrame('03', 'sip', 'Add the sensory impression', 'Describe a personal taste impression without speaking for everyone.')}</div><div><h3>Path B / Situation first</h3>${storyFrame('01', 'walk', 'Enter the everyday', 'Begin with the moment of sitting down after a walk.')}${storyFrame('02', 'window', 'Bring in the drink', 'Set the cup by the window and connect the product to the story.')}${storyFrame('03', 'cup', 'Leave a memory', 'Return to the link between product and situation, not just the scenery.')}</div></div>`, 'Figure 1 | Six original storyboard frames. Not a real shoot, product effect, or client work.')}
    <p>If you swap the second frame in the two paths, the story changes too: an everyday moment may suddenly turn into dense product information, while a specification showcase may gain pauses and atmosphere. This is not a right-or-wrong exercise. It is a reminder that a transition is not only an editing technique; it also changes the order in which readers receive information.</p>
    <p>A storyboard has to be specific before you can see what is missing. “Make it feel natural” is hard to execute; “Place the cup by the window, then use a close shot to show what is inside” gives the frame a clear job. Make the idea clear first, then decide whether complex production is necessary.</p></section>
    <section id="information" class="chapter"><h2>03 / Give the image and information separate jobs</h2>
    ${figure(`<div class="table-scroll" tabindex="0" role="region" aria-label="Shot, caption, and information roles table; scroll horizontally"><table><caption>One point does not need to be repeated at every layer</caption><thead><tr><th scope="col">Layer</th><th scope="col">Can handle</th><th scope="col">Avoid</th></tr></thead><tbody><tr><th scope="row">Shot</th><td>Show appearance, action, and usage context</td><td>Use an atmospheric image as fake proof of a product effect</td></tr><tr><th scope="row">Caption</th><td>Add a name or condition the image cannot show</td><td>Pack in every detail at once, leaving no time to read</td></tr><tr><th scope="row">Narration</th><td>Explain a personal reaction and reason for choosing</td><td>Present one person’s taste as something everyone will like</td></tr></tbody></table></div>`, 'Figure 2 | A narrative division-of-labor table: keep text selectable so readers can compare it with the content as they watch.')}
    <p>If the image clearly shows ice, the caption does not necessarily need to say, “There is ice inside.” Captions can add a condition the image cannot explain; conversely, the single word “refreshing” cannot replace a specific description of mouthfeel. Removing repetition may make the content easier to understand.</p>
    <aside class="margin-note"><strong>Try watching the video another way</strong><p>Watch once with the sound off and note what you understand; then listen to the audio alone and see which information gets added. Finally, watch it in full and ask: are the two layers complementing each other, or repeating the same thing?</p></aside>
    <p>This exercise can help you take a story apart, but it cannot prove which video will sell better. Actual performance is also shaped by the audience, publishing context, price, and many other factors. An everyday style is not a reason to hide a commercial relationship; the way something is filmed and the clarity of the collaboration disclosure are separate matters.</p></section>
    <div class="source-note"><h2>Editorial and material notes</h2><p>This article and all six frames are original narrative exercises; the drink and scenes are illustrative. No real brand packaging, client footage, or performance data was used, and no filming style is presented as having a guaranteed sales advantage.</p></div>`,
    cover: {
      headline: ['One drink,', 'two stories.'],
      sub: ['Show the product first,', 'or step into an everyday moment.'],
      category: 'Content studies / 02',
      labels: ['PRODUCT', 'MOMENT']
    }
  },
  'creator-view-distribution-notes': {
    title: 'Beyond average views: use one table to understand the ups and downs in a creator’s recent content',
    description: 'Using ten synthetic post records, calculate the mean and median views, then use a bar chart to see how a high view count changes the summary numbers.',
    category: 'Practical notes',
    coverAlt: 'Olive paper strips of different lengths arranged on a sheet, with one longer brick-red strip, as a visual metaphor for variation in values.',
    caption: 'AI-generated concept illustration | The paper strips are only a visual metaphor for a distribution, not actual values; see the table and chart below for exact data.',
    toc: [
      ['sample', 'Lay out the ten records first'],
      ['distribution', 'What the mean and median each tell you'],
      ['record', 'Record the conditions behind every number']
    ],
    body: `<p class="lead">When you see “average views: 5,000,” you may picture every piece of content landing somewhere near 5,000. But it could also mean nine posts sit between 1,000 and 3,000 while one reaches 30,000. Those impressions are very different, and one average may not explain the difference.</p>
    <p>Instead of using a real account, we will practice with ten synthetic records listed for public teaching purposes. They are not a market benchmark, campaign result, or forecasting model, only an example that anyone can recalculate. The goal is not to find the prettier number, but to see what the summary leaves out.</p>
    <section id="sample" class="chapter"><h2>01 / Lay out the ten records first</h2><p>Assume that, at one observation point, we record views for ten posts in the same format: 1,200, 1,500, 1,800, 2,000, 2,200, 2,400, 2,600, 3,000, 3,300, 30,000. For teaching convenience, the table below is sorted from low to high; it is not the actual publishing order.</p>
    ${figure(`<div class="table-scroll" tabindex="0" role="region" aria-label="Ten synthetic post records; scroll horizontally"><table><caption>Synthetic data / no real account; unit: views</caption><thead><tr><th scope="col">Post</th><th scope="col">Publication date</th><th scope="col">Format</th><th scope="col">Views</th><th scope="col">Observation time</th></tr></thead><tbody>${views.map((value, index) => `<tr><th scope="row">Example ${String(index + 1).padStart(2, '0')}</th><td>Not specified</td><td>Same-format short video (assumed)</td><td>${formatNumber(value)}</td><td>Same point in time (assumed)</td></tr>`).join('')}</tbody></table></div>`, 'Figure 1 | Synthetic data record table. “Not specified” reminds us that this example cannot compare performance after the same number of days since publication.')}
    <p>The data itself has gaps, and it is better to label them directly. If the original record has no publication dates, you cannot treat “the ten most recent posts” as a sample at the same stage of maturity; if several formats are mixed together, separate them first. Confirming the comparison conditions is often more important than adding another score.</p></section>
    <section id="distribution" class="chapter"><h2>02 / What the mean and median each tell you</h2><p>The mean is the total divided by the number of records. The total views here are 50,000; divided by 10, that gives <strong>5,000</strong>. For the median, sort the values first; with ten records, take the average of the middle 5th and 6th values: (2,200 + 2,400) ÷ 2 = <strong>2,300</strong>.</p>
    ${figure(`<div class="chart" role="img" aria-label="Bar chart of ten synthetic view counts; the final 30,000 is well above the other nine. Mean 5000, median 2300."><div class="chart-summary"><span>Mean <b>${formatNumber(mean)}</b></span><span>Median <b>${formatNumber(median)}</b></span></div><div class="plot">${[0, 10000, 20000, 30000].map(value => `<div class="gridline" style="bottom:${value / 30000 * 100}%"><span>${value / 1000}k</span></div>`).join('')}<div class="reference mean" style="bottom:${mean / 30000 * 100}%"></div><div class="reference median" style="bottom:${median / 30000 * 100}%"></div><div class="bars">${views.map((value, index) => `<div class="bar" style="height:${value / 30000 * 100}%" title="Example ${index + 1}: ${formatNumber(value)} views"><span>${String(index + 1).padStart(2, '0')}</span></div>`).join('')}</div></div><p class="chart-key">Solid line: mean ${formatNumber(mean)} / Dashed line: median ${formatNumber(median)}<br>Horizontal axis: example post number; vertical axis: views (k = thousands). Exact values are in the table above.</p></div>`, 'Figure 2 | The chart and table use the same synthetic records, and the vertical axis starts at zero; high values are not truncated to make the distribution look prettier.')}
    <p>The mean is higher than the median here because the 30,000-view post pulls the average upward. To understand the effect, you could temporarily calculate only the first nine records; the mean is about 2,222. That is a sensitivity exercise, not a replacement for the full result, and it does not mean that the post should be deleted. A high value may be meaningful content, not evidence of a data error.</p>
    <p>The median is less affected by the magnitude of one high value, but it also leaves information out: if you look only at the median, you will not see the 30,000 post. Read the mean, median, and post-by-post distribution together instead of choosing the number that best fits your expectations. For the calculation concept, see <a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda351.htm">NIST’s explanation of measures of location</a>.</p></section>
    <section id="record" class="chapter"><h2>03 / Record the conditions behind every number</h2><p>When you organize real data, record at least the publication date, content format, views, and observation time. If you know about promotion, collaboration, or an unusual publishing context, add a note; if you do not know, leave it unknown. Do not use fluctuations in views to guess at fake followers, purchased traffic, or platform penalties; this table cannot prove those causes.</p>
    <aside class="margin-note"><strong>Try a two-layer summary</strong><p>In the first layer, state the sample scope and observation time. In the second, list the mean, median, highest, and lowest values, then attach the post-by-post records. Let readers move from the conclusion back to the original numbers instead of asking them to trust one isolated average.</p></aside>
    <p>Ten records are only a practice size, not a standard sample for any platform. Likewise, do not combine “views” across platforms before confirming that the metric means the same thing. If your question is whether an audience fits a piece of content, look back at the topic, language, and presentation as well as the numbers; view count cannot answer those questions by itself.</p></section>
    <div class="source-note"><h2>Data and source</h2><p>The ten records were created by the ZhenguoCool editorial team for teaching and do not correspond to a real account or client. The mean and median use standard definitions; the remaining sections present an editorial organizing method. Reference: <a href="https://www.itl.nist.gov/div898/handbook/eda/section3/eda351.htm">NIST/SEMATECH e-Handbook: Measures of Location</a> (accessed 2026-09-05).</p></div>`,
    cover: {
      headline: ['Beyond the average,', 'there is variation.'],
      sub: ['One number', 'is not the whole story.'],
      category: 'Practical notes / 03',
      labels: ['MEAN', 'MEDIAN']
    }
  }
};
