export const enNews = {
  'youtube-auto-dubbing-review': {
    title: 'After YouTube’s Auto-Dubbing Update: Check the Voice Before Publishing',
    description: 'Starting from YouTube’s 2026 auto-dubbing update, use a short spoken script to check proper names, numbers, negations, and tone—and leave a listening checklist before publishing.',
    category: 'Practical notes',
    coverAlt: 'A microphone, headphones, blank notebook, and pencil on a desk, evoking a fictional pre-publication voice-checking scene.',
    caption: 'AI-generated fictional scene illustration | Listen carefully to every line before deciding whether to publish; not an actual YouTube Studio screen or account data.',
    toc: [
      ['why-review', 'Separate “can be translated” from “ready to publish”'],
      ['workflow', 'Build a repeatable listening-check workflow'],
      ['practice', 'Test keywords with a fictional introduction']
    ],
    body: [
      '<p class="lead">Auto-dubbing gives the same video another path for people to hear its content, but it does not decide for creators whether proper names, numbers, or tone are correct. Adding one human listening check before publishing is not about chasing a perfect accent; it is about preventing one small mistake from distorting the information.</p>',
      '<p>The YouTube Blog post dated 2026-05-15 introduced automatic translated audio tracks and more natural-sounding voices; that was an official announcement at the time, not a guarantee that the feature is available for every channel, video, or language. YouTube’s Help page also notes that the feature is available only to eligible creators, and availability can vary by channel, video, and language.</p>',
      '<section id="why-review" class="chapter"><h2>01 / Separate “can be translated” from “ready to publish”</h2><p>Auto-dubbing is a generated result, not a line-by-line human translation. YouTube recommends confirming the original video or channel language when uploading; if it is misidentified, the entire dub may be wrong as well. Auto-dubs cannot be edited directly, so when you spot a problem, hold publication and confirm the original language and the options YouTube provides; if you need to make your own dub, see the <a href="https://support.google.com/youtube/answer/13338784?hl=en">official multi-language audio-track guidance</a> separately; that is a different workflow from auto-dubbing. A Chinese-language original does not mean every language will necessarily be available for dubbing, so treat the list actually shown for the video as the current scope.</p><aside class="margin-note"><strong>The limits of this article’s judgment</strong><p>“Pass” only means that this human listening check found no obvious errors; it does not mean the translation is complete, viewers will like it, or the video will increase sales.</p></aside></section>',
      '<section id="workflow" class="chapter"><h2>02 / Build a repeatable listening-check workflow</h2><p>First, turn on manual review in channel settings so the audio track pauses before publication. On desktop, go through Settings, Channel, and Advanced settings to find Allow automatic dubbing, then select Manually review dubs before publishing; save after configuring the full set of languages or the experimental-language scope shown on the page. For a single video, select it from Content, open Languages, and preview one language. The editorial team’s review order is below:</p><figure class="explainer"><ol class="steps"><li><span>01</span><h3>Listen to the original</h3><p>Confirm that names, brand names, numbers, and negative statements are clear in the original recording.</p></li><li><span>02</span><h3>Listen to the dub</h3><p>Replay the same passage, noting pronunciation, pauses, and shifts in tone.</p></li><li><span>03</span><h3>Compare with the text</h3><p>Write any questionable sentence into the transcript; do not approve it based on “I more or less understood it.”</p></li><li><span>04</span><h3>Make a decision</h3><p>Mark it pass, pending, or redo, and record the reason and date.</p></li></ol><figcaption>Figure 1 | Original instructional illustration, not a YouTube Studio UI screenshot; pass, pending, and redo are editorial labels in this article, not platform performance scores.</figcaption></figure><p>If a language does not appear on the page, record it first as “currently unavailable”; do not assume an account malfunction, and do not treat a single successful preview as proof of permanent support. During preview, set headphone volume high enough to hear consonants clearly, but do not substitute your own accent preference for checking the information.</p></section>',
      '<section id="practice" class="chapter"><h2>03 / Test keywords with a fictional introduction</h2><p>Use a fictional product introduction of about 30 seconds for practice, such as “The Morning Mist Cup holds 350 milliliters, not 500 milliliters; it does not include a straw, and hand-washing is recommended.” First write down the original audio word for word, then compare whether the dub retains keywords such as the numbers, units, “not,” “does not include,” and “recommended.” Then listen for tone: has a reminder turned into a command, or a personal impression into a guarantee?</p><figure class="explainer"><div class="table-scroll" tabindex="0" role="region" aria-label="A checklist for reviewing an auto-dubbed fictional product introduction; horizontally scrollable"><table><caption>Sample checklist / fictional content, for editorial practice only</caption><thead><tr><th scope="col">Focus of original line</th><th scope="col">What to listen for</th><th scope="col">What to do when you find a problem</th></tr></thead><tbody><tr><th scope="row">Morning Mist Cup</th><td>Whether the proper name is split apart or replaced with a similar-sounding word</td><td>pending, review the original language</td></tr><tr><th scope="row">350 milliliters</th><td>Whether both the number and unit appear</td><td>redo, do not guess at a correction</td></tr><tr><th scope="row">Not 500 milliliters</th><td>Whether the negative word disappears</td><td>redo, hold publication first</td></tr><tr><th scope="row">No straw / recommended</th><td>Whether the restriction and tone remain clear</td><td>Record the timestamp, then ask someone else to listen</td></tr></tbody></table></div><figcaption>Figure 2 | Original instructional illustration, not a screenshot of the YouTube Languages page; all lines and labels in the table are fictional.</figcaption></figure><p>Afterward, sort the result into three categories: pass means it is understandable at this point with no obvious critical errors; pending means a second person or the original author needs to confirm it; redo means a keyword, number, or negative statement has changed the meaning. None of the three is a performance measure.</p><p class="source-note"><strong>Official facts and editorial guidance (checked: 2026-09-06)</strong><br>Official fact: <a href="https://blog.youtube/creator-and-artist-stories/youtube-auto-dubbing-explained/">YouTube Blog, 2026-05-15</a> explains the background to auto-dubbing; <a href="https://support.google.com/youtube/answer/15569972?hl=en-EN">YouTube Help</a> explains eligibility, language availability, the original language, the fact that dubs cannot be edited directly, and the pre-publication manual-review path. Editorial guidance: the listening order, 30-second script, pass/pending/redo labels, and checklist are original; no real account was tested, and this does not guarantee that Chinese covers every language or that sales will increase.</p>'
    ].join(''),
    cover: {
      headline: ['Change the language,', 'Listen closely.'],
      sub: ['After auto-dubbing,', 'add a human check.'],
      category: 'Practical notes / 04',
      labels: ['SOURCE', 'REVIEW']
    }
  },
  'edits-mobile-video-workflow': {
    title: 'Edits’ One-Year Update: Break a Talking-Head Script into Easy-to-Edit Footage',
    description: 'What creative ideas emerge from Edits’ first anniversary? Starting with the teleprompter and footage organization, practice filming a talking-head segment in three shots, then use one checklist to review captions, sound, and cuts.',
    category: 'Content studies',
    coverAlt: 'A phone, tripod, ceramic cup, and blank storyboard cards arranged on a desk, evoking a fictional shoot for breaking a talking-head segment into editable shots.',
    caption: 'AI-generated fictional scene illustration | Turn one sentence into one editable clip first; not an actual Edits project, interface, or account screenshot.',
    toc: [
      ['official-update', 'What the announcement says—and what is still coming'],
      ['three-shots', 'One sentence, one shot—three takes'],
      ['edit-check', 'Check watchability before and after editing']
    ],
    body: [
      '<p class="lead">A talking-head clip being hard to edit is not necessarily a software problem; it may be that filming packed several ideas into one long shot. Breaking a 30-second introduction into segments with clear jobs makes reshooting, removing pauses, and adding supporting shots easier.</p>',
      '<p>Meta’s 2026-04-22 announcement marking one year of Edits mentioned an in-app teleprompter with adjustable text size and speed; the Ideas tab can hold saved Instagram reels, audio, and notes; templates can also bring up a project structure. The announcement also listed bilingual captions, advanced color adjustments, speed curves, and more complex templates with overlays and keyframes as ongoing development directions. This article does not treat them as features already live for every account.</p>',
      '<section id="official-update" class="chapter"><h2>01 / What the announcement says—and what is still coming</h2><p>This exercise requires no login and includes no real-account testing. Treat the announcement as context: a teleprompter can help you keep a sentence’s order, Ideas can keep inspiration and notes in one place, and a template structure may let you see an editable skeleton first. What ultimately determines whether footage is easy to cut is still whether each shot handles only one clear action.</p><aside class="margin-note"><strong>Keep version differences in view</strong><p>If a feature is missing from your screen, that does not mean you made a mistake; “coming” in an announcement does not mean it is available today in your region, version, or account.</p></aside></section>',
      '<section id="three-shots" class="chapter"><h2>02 / One sentence, one shot—three takes</h2><p>Suppose you need to introduce a fictional desktop fan. Turn the spoken copy into three sentences: “It fits in a small corner of the desk.” “I’ll use a close-up to demonstrate its three fan speeds.” “Even with the sound off, you can see the hand gesture.” Record each sentence three times on its own, leaving a short stretch of quiet before and after; do not link all three into one shot just to save time.</p><figure class="explainer"><div class="frame"><div class="signal-grid"><div class="note-panel"><span class="number">01</span><h3>0–08 seconds | A-roll</h3><p>Explain straight to camera that the small fan sits in the corner of the desk; one claim, one action.</p></div><div class="note-panel"><span class="number">02</span><h3>08–20 seconds | B-roll</h3><p>Use close-ups of the buttons and hand gesture to show details the spoken line cannot convey.</p></div><div class="note-panel"><span class="number">03</span><h3>20–30 seconds | Ending</h3><p>Return to the person and object, leaving room to cut repeated lines.</p></div></div><p><b>Conceptual timeline:</b> One sentence → one shot → one replaceable piece of footage. The timing is only an allocation for this filming exercise, not a platform rule.</p></div><figcaption>Figure 1 | Original instructional illustration, not an Edits timeline or any app UI screenshot; A-roll, B-roll, and the seconds are only a fictional shooting script for this article.</figcaption></figure><p>During filming, treat A-roll as the main explanation and B-roll as evidence or a rhythm change. The three takes do not have to match perfectly; mark “clear wording,” “complete gesture,” or “natural pause” as appropriate. In the edit, choose the take that can be understood first, then use the other two to fill small gaps; do not let filters or templates lead the process.</p></section>',
      '<section id="edit-check" class="chapter"><h2>03 / Check watchability before and after editing</h2><p>Before placing the footage on the timeline, make a short checklist: can each A-roll sentence stand on its own, does B-roll actually add visual information, and have the captions been checked line by line by a person? After exporting, watch it once muted to confirm the actions and captions still carry you through, then listen with sound to check that cuts do not clip word endings and ambient sound does not cover the key points.</p><figure class="explainer"><div class="table-scroll" tabindex="0" role="region" aria-label="A before-and-after editing checklist and comparison table for talking-head footage; horizontally scrollable"><table><caption>Fictional small-fan short / filming checklist and acceptance criteria</caption><thead><tr><th scope="col">Footage</th><th scope="col">What to keep before editing</th><th scope="col">What to check after export</th></tr></thead><tbody><tr><th scope="row">A-roll talking head</th><td>Three takes, silence at sentence starts and ends</td><td>Watch captions muted, listen to word endings with sound</td></tr><tr><th scope="row">B-roll gestures</th><td>Button, speed setting, and object relationship</td><td>Does the image actually match the narration?</td></tr><tr><th scope="row">Captions</th><td>Start with a draft, then check line by line manually</td><td>Do not let captions vouch for incorrect audio</td></tr><tr><th scope="row">Version</th><td>Keep original footage and backup takes</td><td>Record the export date; do not overwrite the master</td></tr></tbody></table></div><figcaption>Figure 2 | Original instructional illustration, not an Edits project check interface; the objects, lines, and workflow in the table are a fictional example from the editorial team.</figcaption></figure><p>The value of this process is turning “easy to edit” into a checkable condition for footage, rather than guessing whether a template will rescue a muddled talking-head clip. You can also change the shot order and see whether the story still works; if it becomes hard to understand, the information is still tied to one long shot.</p><p class="source-note"><strong>Official facts and editorial guidance (checked: 2026-09-06)</strong><br>Official fact: <a href="https://about.fb.com/news/2026/04/one-year-of-edits-built-for-and-with-creators/">Meta Newsroom, 2026-04-22</a> announced the teleprompter, Ideas tab, notes, and template structure, and described bilingual captions, advanced color, speed curves, and more complex templates as future directions. Editorial guidance: the fictional small fan, three-shot timeline, three takes, A-roll/B-roll checklist, and mute/sound check are original exercises; no real account was tested, no app screenshot was used, and this does not claim that any feature is live in every region or that it increases views or sales.</p>'
    ].join(''),
    cover: {
      headline: ['Plan the shots,', 'then edit.'],
      sub: ['One sentence, one task,', 'so shots connect.'],
      category: 'Content studies / 05',
      labels: ['SCRIPT', 'SHOTS']
    }
  },
  'tiktok-search-topic-workshop': {
    title: 'Choosing Topics Through TikTok’s 2026 Trends: Turn Popular Searches into Questions You Can Answer',
    description: 'Starting with TikTok Next 2026’s search-and-discovery observations, use a commuter bag as an example to turn vague popular topics into specific questions, evidence shots, and a reusable topic-planning sheet.',
    category: 'Social observations',
    coverAlt: 'A commuter shoulder bag, umbrella, and notebook on a wooden table by a window, evoking a fictional scene for turning search questions into short-video topics.',
    caption: 'AI-generated fictional scene illustration | Start with one everyday question and look for evidence; not actual TikTok search data, account information, or post screenshots.',
    toc: [
      ['trend-context', 'First understand what a trend report can say'],
      ['question-map', 'Turn commuter-bag needs into questions'],
      ['small-plan', 'A small worksheet you can use without tools']
    ],
    body: [
      '<p class="lead">Popular searches can show what words people are looking for, but they cannot directly answer “why someone is searching” or “whether they believe the answer.” They certainly cannot replace needs interviews or sales data. The first step in choosing a topic is to step back from the heat and ask a question you can genuinely answer on camera.</p>',
      '<p>The TikTok Next trend forecast published on 2026-01-14 describes Curiosity Detours as a behavioral direction toward more active exploration and taking a detour to discover answers. It is TikTok’s forecast about platform culture, not an independent study of users in Taiwan; this article does not cite survey figures from the report or treat it as a proven need among Taiwanese audiences.</p>',
      '<section id="trend-context" class="chapter"><h2>01 / First understand what a trend report can say</h2><p>A trend report is useful for proposing a hypothesis that viewers may want to see how a question gets solved, not for proving that a topic will go viral. On 2024-03-13, TikTok introduced Creator Search Insights and explained that users in some regions can see search topics, categories, For You, and content gap; the entry point can be found by typing its name in the app’s search bar, while actual availability depends on the app and TikTok’s official guidance.</p><aside class="margin-note"><strong>Do not conflate these terms</strong><p>“Lots of searches” is a visible behavioral signal on the platform; “there is a need” requires more context; “will buy” is another proposition this exercise has not established.</p></aside></section>',
      '<section id="question-map" class="chapter"><h2>02 / Turn commuter-bag needs into questions</h2><p>The fictional “commuter bag” below is only an exercise: it does not pull any real posts or fill in platform data. Each question should be answerable in one limited shot, with the scope of the title stated clearly; if the only possible descriptions are “super useful” or “must buy,” there is not yet verifiable evidence.</p><figure class="explainer"><div class="table-scroll" tabindex="0" role="region" aria-label="A topic-planning table from commuter-bag needs to filmable evidence; horizontally scrollable"><table><caption>Original topic-planning example / fictional commuter bag, not TikTok search results</caption><thead><tr><th scope="col">Vague need</th><th scope="col">Question you can answer</th><th scope="col">Evidence shot</th><th scope="col">Scoped title</th></tr></thead><tbody><tr><th scope="row">Worried things will get damp</th><td>Where on the inside can water marks be seen after a small amount of water drips?</td><td>Empty bag, no electronic items, record drip amount and observation time</td><td>Inside a commuter bag: observation record after light dripping</td></tr><tr><th scope="row">Worried a laptop will be hard to fit</th><td>How can a laptop be put in without pressing on the cables?</td><td>Continuous sequence of putting it in, closing the bag, and taking it out</td><td>Commuter-bag storage: order for putting in one laptop</td></tr><tr><th scope="row">Want to find small items</th><td>Where should keys go for quicker access?</td><td>A single fixed pocket and one insert/remove demonstration</td><td>See one small-item pocket’s location in 30 seconds</td></tr></tbody></table></div><figcaption>Figure 1 | Original instructional illustration, not TikTok search data, real posts, or a UI screenshot; the questions, shots, and titles are fictional examples from the editorial team. Dripping is only a limited observation and does not represent general water resistance.</figcaption></figure><p>When filming, do not casually copy someone else’s wording or shots. Write your own question first, then decide which visible condition to show; if the camera cannot answer it, narrow the title or mark it for research instead of using popularity to fill an evidence gap.</p></section>',
      '<section id="small-plan" class="chapter"><h2>03 / A small worksheet you can use without tools</h2><p>Creator Search Insights does not guarantee that every Taiwan account can see it; actual availability depends on the app and TikTok’s official guidance. The Help page can be a reference for further reading, but this article does not treat account-by-account eligibility that has not been checked as a universal rule. If you cannot find the entry point, do not work around the restriction or treat search-bar results as complete market data; work through one round using your own question worksheet first.</p><figure class="explainer"><ol class="steps"><li><span>01</span><h3>Collect your own questions</h3><p>Write down the original wording of a commuting, storage, or usage pain point; do not copy post titles.</p></li><li><span>02</span><h3>Narrow the answerable scope</h3><p>Let one short video answer one question, and write first what it cannot prove.</p></li><li><span>03</span><h3>Plan the evidence shots</h3><p>Film one action, one limitation, and one result you can review.</p></li></ol><figcaption>Figure 2 | Original instructional illustration, not a TikTok tool workflow or UI screenshot; the three steps are this article’s manual topic-planning method.</figcaption></figure><p>After publishing, do not look only at whether the topic drew views. Review whether comments pursue the same question, challenge a particular condition, or respond only to the editing style; put the new question into the next worksheet. This way, search signals are only a starting point—visual evidence and readers’ follow-up questions are what make topic selection more concrete over time.</p><p class="source-note"><strong>Official facts and editorial guidance (checked: 2026-09-06)</strong><br>Official fact: <a href="https://newsroom.tiktok.com/introducing-tiktok-next-2026-our-trend-forecast-for-marketers-for-the-year-ahead-ca?lang=en-CA">TikTok Newsroom, 2026-01-14</a> is the platform’s forecast for 2026; <a href="https://newsroom.tiktok.com/creator-search-insights?lang=en">TikTok Newsroom, 2024-03-13</a> describes Creator Search Insights as having been introduced in some regions and mentions categories, For You, and content gap. <a href="https://support.tiktok.com/en/using-tiktok/growing-your-audience/creator-search-insights">TikTok Help</a> is provided as further reading; availability depends on the app and official guidance. This article does not claim availability in Taiwan or treat account-by-account eligibility that has not been checked as a universal rule. Editorial guidance: the commuter-bag table, three-step method, and distinction among “searches,” “needs,” and “sales” are original exercises; no data was collected and no sales forecast was made.</p>'
    ].join(''),
    cover: {
      headline: ['Follow the question,', 'find the topic.'],
      sub: ['Don’t just chase trends,', 'show a useful answer.'],
      category: 'Social observations / 06',
      labels: ['SEARCH', 'ANSWER']
    }
  }
};
